### ISSUE TITLE
PhantomJS has been discontinued, but the tests do rely on it

### ISSUE THREAD

**Issue by kix** [nnichols/brew-bot#8]
**Describe the bug**
As [the official sources say](https://github.com/ariya/phantomjs/issues/15344), PhantomJS is archived since Mar 2018.

**To Reproduce**
Just try to install PhantomJs with any deprecation-aware package manager such as Homebrew.

**Expected behavior**
No changes in behaviour expected

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser PhantomJS/Chrome/Chromium
 - Version: any

**Comment by kix** [comment]
Options are: CasperJS, Puppeteer

**Comment by nnichols** [comment]
@kix good call. I'll test and migrate the lein commands
